### ISSUE TITLE
ExoPlayer DefaultHttpDataSource

### ISSUE THREAD

**Issue by furkanaskin** [furkanaskin/podpocket#3]
**Describe the bug**
Some links can't playing on ExoPlayer. When i check the links, they can playable links, downloading directly. No problem for server side, we need the configure DefaultHttpDataSource, check screenshot below.

// Usually, home screen-recommended episodes can't playable.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-05-17 at 22 21 58" src="https://user-images.githubusercontent.com/22769589/58004192-55fc1d80-7aeb-11e9-931e-7b1559250c61.png">

**Comment by yusufcakmak** [comment]
there is a redirect problem, you can try allowCrossProtocolRedirects. 

> The problem described in the issue is about cross-protocol redirects (from http to https or vice versa). Exoplayer supports this, but you have to set allowCrossProtocolRedirects to true. Regular redirects (including 301 redirects) are supported by default. The redirect you're receiving is most likely a cross-protocol redirect.

https://stackoverflow.com/questions/41517440/exoplayer2-how-can-i-make-a-http-301-redirect-work

**Comment by furkanaskin** [comment]
[Fixed - ExoPlayer DefaultHttpDataSourceFactory added.](https://github.com/furkanaskin/podpocket/commit/98ddf7bdd641e90761d067374eb0d5d3eb3b4a3f)
